{-# LANGUAGE QuasiQuotes #-}
-- Nftables.hs
module I3 (i3Config, i3StatusConfig) where

import Quasiquote (config)

i3Config :: String
i3Config =
  [config|# This file is under control of Propellor.

# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#
# https://i3wm.org/docs/userguide.html
# https://itsfoss.com/i3-customization
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Start XDG autostart .desktop files using dex. See also
# https://wiki.archlinux.org/index.php/XDG_Autostart
exec --no-startup-id dex --autostart --environment i3

# The combination of xss-lock, nm-applet and pactl is a popular choice, so
# they are included here as an example. Modify as you see fit.

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
exec --no-startup-id nm-applet

# Set background
exec xsetroot -solid black

# Use pactl to adjust volume in PulseAudio.
set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status

bindsym $mod+KP_Add exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym $mod+KP_Subtract exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym $mod+KP_Divide exec --no-startup-id pactl suspend-sink @DEFAULT_SINK@ true
bindsym $mod+KP_Multiply exec --no-startup-id pactl suspend-sink @DEFAULT_SINK@ false
bindsym $mod+KP_Enter exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle

# Hide cursor shortcut
bindsym $mod+c exec --no-startup-id ~/bin/togglecursor

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
#bindsym $mod+Return exec i3-sensible-terminal
bindsym $mod+Return exec xterm
bindsym $mod+Ctrl+Return exec xterm -title "float term" 
bindsym $mod+Shift+Return exec xterm -title "float ghci" -e "exec ghci"
bindsym $mod+Ctrl+Shift+Return exec xterm -title "float python" -e "exec python"

# kill focused window
bindsym $mod+BackSpace kill
bindsym $mod+Shift+BackSpace exec pkill -9 racket

# x-kill (the Grim Reaper himself)
bindsym $mod+Delete exec xkill

# start dmenu (a program launcher)
bindsym $mod+p exec --no-startup-id dmenu_run
# A more modern dmenu replacement is rofi:
# bindcode $mod+40 exec "rofi -modi drun,run -show drun"
# There also is i3-dmenu-desktop which only displays applications shipping a
# .desktop file. It is a wrapper around dmenu, so you need that installed.
# bindcode $mod+40 exec --no-startup-id i3-dmenu-desktop

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# previous/next from full screen
bindsym $mod+Mod1+Left fullscreen toggle; focus left; fullscreen toggle
bindsym $mod+Mod1+Down fullscreen toggle; focus down; fullscreen toggle
bindsym $mod+Mod1+Up fullscreen toggle; focus up; fullscreen toggle
bindsym $mod+Mod1+Right fullscreen toggle; focus right; fullscreen toggle

# alternatively, you can use the cursor keys:
bindsym $mod+Ctrl+Left move left
bindsym $mod+Ctrl+Down move down
bindsym $mod+Ctrl+Up move up
bindsym $mod+Ctrl+Right move right

# Mark and swap
#bindsym $mod+m mark swapsrc
#bindsym $mod+Shift+m swap container with mark swapsrc

# read 1 character and mark the current window with this character
bindsym $mod+m exec i3-input -F 'mark %s' -l 1 -P 'Mark: '

# read 1 character and go to the window with the character
bindsym $mod+g exec i3-input -F '[con_mark="%s"] focus' -l 1 -P 'Goto: '

# split in horizontal orientation
bindsym $mod+h split h
bindsym $mod+Shift+h layout splith

# split in vertical orientation
bindsym $mod+v split v
bindsym $mod+Shift+v layout splitv

# enter fullscreen mode for the focused container
bindsym $mod+space fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+b layout tabbed
bindsym $mod+d layout default
bindsym $mod+s layout stacking
bindsym $mod+Shift+space layout toggle split

# toggle tiling / floating
bindsym $mod+Escape floating toggle

# change focus between tiling / floating windows
bindsym $mod+f focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
bindsym $mod+Shift+a focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10

# previous/next, back and forth
bindsym $mod+Tab workspace next
bindsym $mod+Next workspace next
bindsym $mod+Shift+Tab workspace prev
bindsym $mod+Prior workspace prev
bindsym $mod+equal workspace back_and_forth
bindsym $mod+Shift+equal move container to workspace back_and_forth

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10

# Screen lock, suspend, hibernate controls
#bindsym $mod+ exec 
bindsym $mod+End exec --no-startup-id i3lock
bindsym $mod+Shift+End exec --no-startup-id systemctl suspend -i
bindsym $mod+Shift+Ctrl+End exec --no-startup-id systemctl hibernate

# Convenience shortcuts
bindsym $mod+e exec emacsclient -nc -a ""
bindsym $mod+w exec librewolf --new-window

# Browse URL from clipboard
#bindsym $mod+u --release exec --no-startup-id chromium --new-window "$(xclip -o -selection clipboard)"
bindsym $mod+u --release exec --no-startup-id librewolf --new-window  "$(xsel)"
bindsym $mod+i --release exec --no-startup-id dillo  "$(xsel)"

# Play video URL from clipboard
# bindsym $mod+Shift+y --release exec --no-startup-id mpv "$(xclip -o -selection clipboard | sed -e 's/[?&]t=[^&]*//')"
bindsym $mod+Shift+y --release exec --no-startup-id mpv "$(xsel | sed -e 's/[?&]t=[^&]*//')"
# bindsym $mod+y --release exec --no-startup-id mpv "$(xclip -o -selection clipboard)"
bindsym $mod+y --release exec --no-startup-id mpv "$(xsel)"

# Application launchers: press $mod+/ followed by a followup key
set $mode_launcher Launch: [b]rave [c]hromium [k]eepassxc [l]ibreoffice [m]usikcube [n]yxt tor-br[o]wser [l]ibreoffice [t]hunderbird
bindsym $mod+slash mode "$mode_launcher"

# Commands can be chained (;) and the mode "default" automatically exits
mode "$mode_launcher" {
    bindsym b exec brave --new-window; mode "default"
    bindsym c exec chromium --new-window; mode "default"
    bindsym k exec keepassxc; mode "default"
    bindsym l exec libreoffice; mode "default"
    bindsym m exec xterm -title "float musikcube" -e "exec musikcube"; mode "default"
    bindsym n exec nyxt; mode "default"
    bindsym o exec tor-browser; mode "default"
    bindsym t exec thunderbird; mode "default"

    bindsym Escape mode "default"
    bindsym Return mode "default"
}

# No titlebar and Floaters
for_window [class="^.*"] border pixel 2
for_window [title="float"] floating enable
for_window [title=" - mpv"] floating enable
for_window [title=" - cvlc"] floating enable

# Colors
# client.focused         #4c7899 #285577 #ffffff #2e9ef4   #285577
# client.focused_inactive #333333 #5f676a #ffffff #484e50   #5f676a
# class                 border  backgr. text    indicator child_border
client.focused          #4c7899 #8b0000 #ffffff #2e9ef4   #ff0000
client.focused_inactive #333333 #5f676a #ffffff #ff0000   #5f676a
client.unfocused        #333333 #222222 #888888 #292d2e   #222222
client.urgent           #2f343a #900000 #ffffff #900000   #900000
client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c

client.background       #ffffff

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+q exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# Convenient resizing.
bindsym $mod+Shift+Left resize shrink width 5 px or 5 ppt
bindsym $mod+Shift+Up resize grow height 5 px or 5 ppt
bindsym $mod+Shift+Right resize grow width 5 px or 5 ppt
bindsym $mod+Shift+Down resize shrink height 5 px or 5 ppt

# resize window (you can also use the mouse for that)
# mode "resize" {
#         # These bindings trigger as soon as you enter the resize mode

#         # Pressing left will shrink the window’s width.
#         # Pressing right will grow the window’s width.
#         # Pressing up will shrink the window’s height.
#         # Pressing down will grow the window’s height.
#         bindsym j resize shrink width 10 px or 10 ppt
#         bindsym k resize grow height 10 px or 10 ppt
#         bindsym l resize shrink height 10 px or 10 ppt
#         bindsym semicolon resize grow width 10 px or 10 ppt

#         # same bindings, but for the arrow keys
#         bindsym Left resize shrink width 10 px or 10 ppt
#         bindsym Down resize grow height 10 px or 10 ppt
#         bindsym Up resize shrink height 10 px or 10 ppt
#         bindsym Right resize grow width 10 px or 10 ppt

#         # back to normal: Enter or Escape or $mod+r
#         bindsym Return mode "default"
#         bindsym Escape mode "default"
#         bindsym $mod+r mode "default"
# }

# bindsym $mod+r mode "resize"

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3status
}
|]

i3StatusConfig :: String
i3StatusConfig =
  [config|# This file is under control of Propellor.
         
general {
  colors = true
  color_good = "#a3be8c"
  color_bad  = "#bf616a"
  color_degraded = "#ebcb8b"
  interval = 1
  separator = "|"
}

cpu_usage {
  format = "CPU_0: %cpu0 CPU_1: %cpu1 CPU_2: %cpu2 CPU_3: %cpu3"
  degraded_threshold = 90
  max_threshold = 95
}

memory {
  memory_used_method = classical
  format="Memory: %used/%total"
}

disk "/" {
  format = "/: %percentage_used"
}

disk "/home" {
  format = "/home: %percentage_used"
}

disk "/boot" {
  format = "/boot: %percentage_used"
}

# ethernet ens5 {
#   format_up = "ETH: %ip (%speed)"
#   format_down = "ETH: down"
# }

# wlp3s0
#wireless __first__ {
#  format_up = "WLS: (%quality at %ssid) %ip"
#  format_down  = "WLS: down"
#}

tztime amsterdam {
        format = "<span foreground='#ffffff'>time:</span> %time"
        # format_time = " %Y-%m-%d %H:%M:%S %Z"
        timezone = "Europe/Amsterdam"
        hide_if_equals_localtime = true
}

battery all {
  path=/sys/class/power_supply/%d/uevent
  format = "BAT AGGR: %percentage"
  last_full_capacity = true
  threshold_type=percentage
  low_threshold=10
}

order += "cpu_usage"
order += "memory"
order += "disk /"
order += "disk /boot"
order += "disk /home"
# order += "ethernet ens5"
#order += "wireless __first__"
order += "battery all"
order += "timezone amsterdam"
|]
